#' Create several bin objects simultaneously from a table
#'
#' Given a table of contigs and the bins that they belong to, create gbtbin
#' objects with corresponding bins from the parent gbt object. The table is
#' generated by the accessory script parse_bin_fasta_files.pl
#'
#' @param x Object of class gbt representing the parent metagenome
#' @param file Table of contig names and bin names, produced by the parse_bin_fasta_files.pl script
#'
#' @return Creates objects of class gbtbin as side effect
#' @seealso \code{\link{gbt}}
#' @seealso \code{\link{gbtbin}}
#' @export
#'

importBins <- function(x, # Object of class gbt
                       file # File with table of bins (1st col) and contig names (2nd col)
                       ) {
    thetab <- read.table(file=file, sep="\t",header=F)
    names(thetab) <- c("bin","contig")
    binsvector <- as.vector(levels(thetab$bin))
    # Create a dummy function assignfunc() because assign() works by side-effect!
    assignfunc <- function(y) assign(as.character(binsvector[y]),
                                     gbtbin.default(shortlist=as.vector(thetab$contig[which(thetab$bin==binsvector[y])]),
                                                    x=x,
                                                    slice=1
                                                    ),
                                     env=.GlobalEnv
                                     )
    for (i in 1:length(binsvector)) {
        assignfunc(i)
    }
}